config/routes.rb
Rails.application.routes.draw do
  get 'landing/show'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users
  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "sign_in", to: redirect("landing")
  get "sign_in" => "sessions#new"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  resources :album_views
  resources :friends do
    member do
      get 'albums'
    end
  end

  get '/albums', to: 'albums#index'

  get "/main/form" => "main#form", as: "main_form"
  resources :main

  resources :albums do
    collection do
      post 'create', as: "create_album"
      post 'new', as: "new_album"
    end
    member do
      post 'photos/new'
      get '/map' => "albums#map", as:"map"
      post 'photos/create'
      get 'form', as: "album_form"
      resources :photos do
        member do
          get 'edit', to: "photos#edit"
          post 'update'
          delete 'delete', to: "photos#destroy"
        end
      end
    end
  end

  resources :photos do
    member do
      get 'edit', to: "photos#edit"
      post 'update'
    end
  end

  post "photos/create"

  post 'album_view/new'
  post 'album_view/create'

  resources :users
  resources :accounts

  get 'account/settings', as: "account_settings"
  get 'account/edit', as: "account_edit"
  delete 'account/sign_out', to: "sessions#destroy"
  patch 'account/save'

  get 'landing/show'

   get '/landing', to:"landing#show"

  get '/login', to:"login#login"

  get '/main', to:"main#index"

  get '/albums', to:"albums#index"

  get 'friends/index'
  get '/friends', to:"friends#index"
  post '/friends/index'
  post '/friends', to:"friends#index"
  get 'friends/results'
  post 'friends/results'

  post 'users/edit_pic'

   root 'landing#show'

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :require_login

  def index
    @nav_bar = true
    @all_users = User.all
    @get_friend_reqs = Popular::Friendship.where(friend_id:current_user.id)


    #When one user friends another
    if params[:friend]
		friend = @all_users.find(params[:friend].to_i)
		current_user.befriend friend
		#friend_requests = Popular::Friendship.where(popular_model_id:current_user.id)
	  end

	#When the friend accepts the request
	if params[:accept]
    	Popular::Friendship.find(params[:accept].to_i).update_attribute(:did_accept, true)
        #@friend_shown_array = Popular::Friendship.where(popular_model_id:current_user.id).to_a.clone
    end

    #If friend rejects request
    if params[:reject]
    	User.find(params[:reject].to_i).unfriend current_user
    end

    #Updating all user's friends
	@all_friends = Array.new
	@user_friender = Popular::Friendship.where(popular_model_id:current_user)
    @user_friendee = Popular::Friendship.where(friend_id:current_user)

    #might need to check if user friender/friendee is null
    @user_friender.each do |f|
    if f.did_accept != nil
    		User.find(f.friend_id).first_name
        	@all_friends.push(User.find(f.friend_id))
    	end
    end

    @user_friendee.each do |f|
    	if f.did_accept != nil
            User.find(f.popular_model_id).first_name
            @all_friends.push(User.find(f.popular_model_id))
        end
    end

    #When user wants to remove a friend
    #Need to check who friended who to determine how to remove the friendship
    if params[:remove]
    	if current_user.friends_with? User.find(params[:remove].to_i)
	     	Popular::Friendship.where(popular_model_id:current_user).each do |p|
	     		if User.find(p.friend_id).id == params[:remove].to_i
	     			current_user.unfriend (User.find(params[:remove].to_i))
	     		end
	     	end
	     elsif User.find(params[:remove].to_i).friends_with? current_user
	     	Popular::Friendship.where(popular_model_id:params[:remove].to_i).each do |p|
	     		if User.find(p.friend_id).id == current_user.id
	     			User.find(params[:remove].to_i).unfriend current_user
	     		end
	     	end
		end
    end
  end

  def results
    @nav_bar = true
  	@users = User.all
  	@name = params[:s]

    @results = Array.new

    @users.each do |user|
    	if user.first_name.downcase.include?(@name.downcase) || (user.last_name && user.last_name.downcase.include?(@name.downcase) || user.email.downcase.include?(@name.downcase))
        #First name is required, but last is not
        #Exclude self, exclude if already has person as friend
        if user.id != current_user.id && (!(user.friended_by? current_user) && !(current_user.friended_by?(user)))
          @results.push(user)
        end
      end
    end
  end

  def albums
    @nav_bar = true
    @albums = Album.where(user_id: params[:id], isPublic: true)
    @galleries_viewonly = Array.new
    @galleries_upload = Array.new
    others = Album.where(user_id: params[:id], isPublic: false)
    others.each do |a|
        views = AlbumView.where(album_id: a.id)
        views.each do |v|
          #view_upload_access 0->viewonly, 1->upload+view
          sharables = AlbumView.where(album_view_id: v.album_view_id, user_id: current_user.id)
          if !sharables.blank?
            sharables.each do |sharable|
              if sharable.view_upload_access == 1
                my_album = Album.find(sharable.album_view_id)
                name = a.album_name
                @galleries_upload.push([my_album, name])
              elsif sharable.view_upload_access == 0
                @galleries_viewonly.push(a)
              end
            end
          end
        end
    end
  end
end

app/views/friends/albums.html.erb
<section id="portfolio" class="portfolio">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1 text-center">
                    <h2><%= User.where(id: params[:id]).first.first_name%>'s Albums</h2>
                    <hr class="small">
                    <div class="row">

                      <table>
                          <tbody>
                            <% if @albums.blank? && @galleries_viewonly.blank? && @galleries_upload.blank? %>
                              <p> This friend doesn't have any albums yet </p>

                            <% else %>
                              <div>
                                <% if !@albums.blank? %>
                                  <% @albums.each do |album| %>
                                  <!-- %= render :layout =>'layouts/listbackground' do % -->
                                  <div class="col-sm-4 col-md-2">
                                    <div class="thumbnail text-center">
                                      <%if sample_photo(album.id)%>
                                        <%=image_tag sample_photo(album.id).image.url(:med), id:"album_image"%>
                                      <%else%>
                                        <%=image_tag "480px-Placeholder.png", id:"placeholder"%>
                                      <%end%>
                                      <div class="caption overflow">
                                        <p><%= link_to album.album_name, album, id: "album_name_listing"%></p>
                                      </div>
                                      <br/>
                                  </div>
                                  <% end %>
                                <% end %>
                                <% if !@galleries_viewonly.blank? %>
                                  <% @galleries_viewonly.each do |gallery| %>
                                  <div class="col-sm-4 col-md-2">
                                    <div class="thumbnail text-center">
                                      <%if sample_photo(gallery.id)%>
                                        <%=image_tag sample_photo(gallery.id).image.url(:med), id:"album_image"%>
                                      <%else%>
                                        <%=image_tag "480px-Placeholder.png", id:"placeholder"%>
                                      <%end%>
                                      <div class="caption overflow">
                                        <p><%= link_to gallery.album_name, gallery, id: "album_name_listing"%></p>
                                      </div>
                                      <br/>
                                  </div>
                                  <% end %>
                                <% end %>
                                <% if !@galleries_upload.blank? %>
                                  <% @galleries_upload.each do |gallery| %>
                                  <div class="col-sm-4 col-md-2">
                                    <div class="thumbnail text-center">
                                      <%if sample_photo(gallery.first.id)%>
                                        <%=image_tag sample_photo(gallery.first.id).image.url(:med), id:"album_image"%>
                                      <%else%>
                                        <%=image_tag "480px-Placeholder.png", id:"placeholder"%>
                                      <%end%>
                                      <div class="caption overflow">
                                        <p><%= link_to gallery.last, gallery.first, id: "album_name_listing"%></p>
                                      </div>
                                      <br/>
                                  </div>
                                  <% end %>
                                <% end %>
                              </div>
                            <% end %>

                          </tbody>
                        </table>
                </div>
                <!-- /.col-lg-10 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </section>

app/views/friends/results.html.erb
  <section id="portfolio" class="primary">
  <div class="back-button">
      <%= link_to 'Back to friends', "/friends", class: "btn btn-primary" %>
  </div>
  </div>
    <div class="container">
      <div class="row text-center">
        <div class="col-lg-10 col-lg-offset-1">
          <h2> Results </h2>
        	<% if @results.empty? %>
        		<td> There are no results</td>
        	<% else %>
          	<hr class="small">
              <div id="container" style="text-align: center"><!--"margin-left: 5cm;">-->
                    <%= form_tag(friends_results_path, method: "post") do %>
                        <%=label_tag(:s, "New Friend Search:") %>
                        <%= text_field_tag(:s) %>
                        <%= submit_tag "Search", :class => "btn btn-primary" %>
                    <% end %>
                  </div>
              <div class="row">
                <% @results.each do |result| %>
                  <div class="col-sm-6 col-md-4">
                    <div class="thumbnail">
                      <% if result.avatar_id %>
                        <%= image_tag (Photo.find(result.avatar_id).image.url(:large)) %>
                      <% else %>
                        <img src="/assets/no_photo_user.png" style="height:80%;width:80%;" alt="no-photo">
                      <% end %>
                      <div class="caption">
                        <h3><%= result.first_name %> <%= result.last_name %></h3>
                        <p>
                          <%= form_tag("/friends", :action => "index", method: "get") do %>
                            <%= hidden_field_tag(:friend, result.id) %>
                            <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
                              <div>Add as Friend</div>
                            <% end %>
                          <%end%>
                        </p>
                      </div>
                    </div>
                  </div>
                <%end%>
              </div>
            </hr>
          <%end%>
        </div>
        <!-- /.container -->
    </section>
</body>