config/routes.rb
Rails.application.routes.draw do
  get 'landing/show'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users
  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "sign_in", to: redirect("landing")
  get "sign_in" => "sessions#new"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  resources :album_views
  resources :friends do
    member do
      get 'albums'
    end
  end

  get '/albums', to: 'albums#index'

  get "/main/form" => "main#form", as: "main_form"
  resources :main

  resources :albums do
    collection do
      post 'create', as: "create_album"
      post 'new', as: "new_album"
    end
    member do
      post 'photos/new'
      get '/map' => "albums#map", as:"map"
      post 'photos/create'
      get 'form', as: "album_form"
      resources :photos do
        member do
          get 'edit', to: "photos#edit"
          post 'update'
          delete 'delete', to: "photos#destroy"
        end
      end
    end
  end

  resources :photos do
    member do
      get 'edit', to: "photos#edit"
      post 'update'
    end
  end

  post "photos/create"

  post 'album_view/new'
  post 'album_view/create'

  resources :users
  resources :accounts

  get 'account/settings', as: "account_settings"
  get 'account/edit', as: "account_edit"
  delete 'account/sign_out', to: "sessions#destroy"
  patch 'account/save'

  get 'landing/show'

   get '/landing', to:"landing#show"

  get '/login', to:"login#login"

  get '/main', to:"main#index"

  get '/albums', to:"albums#index"

  get 'friends/index'
  get '/friends', to:"friends#index"
  post '/friends/index'
  post '/friends', to:"friends#index"
  get 'friends/results'
  post 'friends/results'

  post 'users/edit_pic'

   root 'landing#show'

end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
#  before_create :generate_authentication_token
  popular

  has_many :friender_friends, foreign_key: :friendee_id, class_name: "Friend"
  has_many :frienders, through: :friender_follows, source: :friender
  has_many :friendee_friends, foreign_key: :friender_id, class_name: "Friend"
  has_many :friendees, through: :friendee_friends, source: :friendee

  validates :password, length: {minimum: 6, too_short: "must be at least six characters long"}


  def generate_authentication_token
    loop do
      self.authentication_token = SecureRandom.base64(64)
      break unless User.find_by(authentication_token: authentication_token)
    end
  end

  # You can also use a symbol here but the friendship won't be passed to your method
 # after_befriend 'notify_friendship_created value'
 # after_unfriend 'notify_unfriended value'

  #def notify_friendship_created(friendship)
   # gon.testFriendship = "#{friendship.popular_model_id} friended #{friendship.friend}"
  #end

  #def notify_unfriended(friendship)
   # puts "#{name} unfriended #{friendship.friend.name}"
  #end

 # @test = User.find(1)
 # @test2 = User.find(2)
 # @test.befriend @test2
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController

  def show
    begin
      user = User.find params[:id]
      render json: user.to_json

    end
  end

  def index
    users = User.all
    render json: users.to_json
  end

  def create
    user = User.create!(email: params[:email], password: params[:password], first_name: params[:first_name])
    render json: user.to_json
  end


end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
#include Clearance::Controller
# Prevent CSRF attacks by raising an exception.
# For APIs, you may want to use :null_session instead.
protect_from_forgery with: :exception

helper UsersHelper


  def index
    @users = User.all
    @test = User.find(1)
    @test2 = User.find(2)
    @test.befriend @test2
  end



  def user_from_params
     @email = user_params.delete(:email)
     @password = user_params.delete(:password)
     @first_name = user_params.delete(:first_name)
     @last_name = user_params.delete(:last_name)
     @birthday = user_params.delete(:birthday)
     @user_name = user_params.delete(:user_name)



     Clearance.configuration.user_model.new(user_params).tap do |user|
       user.email = @email
       user.password = @password
       user.birthday = @birthday
       if @first_name === ""
           user.first_name = nil
       else
           user.first_name = @first_name
       end
       if @last_name === ""
           user.last_name = nil
       else
           user.last_name = @last_name
       end
       if @user_name === ""
           user.user_name = nil
       else
           user.user_name = @user_name
       end
     end
   end


  def update
    if params[:id]="edit_pic"
      @p = Photo.find(params[:dragphoto])
      @a = Album.find(@p.album_id)
      @u = User.find(@a.user_id)
      if @u=current_user
        puts "passed"
        puts params[:x]
        puts params[:y]
        @p.update_attribute(:x_coord, params[:x])
        @p.update_attribute(:y_coord, params[:y])
      else
        puts "failed"
      end


      redirect_to "/main/form"
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def error_list(attribute)
      if @user.errors.include?(attribute)
          @user.errors[attribute].to_a
      else
          []
      end
  end

end

app/views/users/_form.html.erb
  <div class="text-label-field">
    <%= form.label :email %>
  </div>
  <div class="text-label-field">
    <%= form.text_field :email, type: 'email' %>
  </div>
  <%error_list(:email).each do |msg|%>
      <%= render :layout =>'layouts/alert' do %>
          <%'Email ' + msg%>
      <%end%>
  <%end%>


  <div class="text-label-field">
    <%= form.label :password %>
  </div>
  <div class="text-label-field">
    <%= form.password_field :password %>
  </div>
  <%error_list(:password).each do |msg|%>
      <%= render :layout =>'layouts/alert' do %>
          <%'Password ' + msg%>
      <%end%>
  <%end%>


  <div class="text-label-field">
    <%= form.label :user_name %>
  </div>
  <div class="text-label-field">
    <%= form.text_field :user_name %>
  </div>

  <div class="text-label-field">
    <%= form.label :first_name %>
  </div>
  <div class="text-label-field">
    <%= form.text_field :first_name %>
  </div>

  <div class="text-label-field">
    <%= form.label :last_name %>
  </div>
  <div class="text-label-field">
    <%= form.text_field :last_name %>
  </div>

  <div class="text-label-field">
    <%= form.label :birthday%>
  </div>
  <div class="text-label-field">
    <%= form.date_field :birthday %>
  </div>



  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being registered:</h2>
    </div>
  <% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>All Users</h1>
<table class="data-list">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= link_to 'Show', user%></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<section id="portfolio" class="primary">
  <div class="text-label-field"><h2><%= t(".title") %></h2></div>
  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="text-label-field">
      <%= form.submit class: "btn btn-primary" %>
      <%= link_to t(".sign_in"), sign_in_path, class: "btn btn-primary" %>
    </div>
  <% end %>
</section>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>