config/routes.rb
Rails.application.routes.draw do
  get 'landing/show'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users
  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "sign_in", to: redirect("landing")
  get "sign_in" => "sessions#new"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  resources :album_views
  resources :friends do
    member do
      get 'albums'
    end
  end

  get '/albums', to: 'albums#index'

  get "/main/form" => "main#form", as: "main_form"
  resources :main

  resources :albums do
    collection do
      post 'create', as: "create_album"
      post 'new', as: "new_album"
    end
    member do
      post 'photos/new'
      get '/map' => "albums#map", as:"map"
      post 'photos/create'
      get 'form', as: "album_form"
      resources :photos do
        member do
          get 'edit', to: "photos#edit"
          post 'update'
          delete 'delete', to: "photos#destroy"
        end
      end
    end
  end

  resources :photos do
    member do
      get 'edit', to: "photos#edit"
      post 'update'
    end
  end

  post "photos/create"

  post 'album_view/new'
  post 'album_view/create'

  resources :users
  resources :accounts

  get 'account/settings', as: "account_settings"
  get 'account/edit', as: "account_edit"
  delete 'account/sign_out', to: "sessions#destroy"
  patch 'account/save'

  get 'landing/show'

   get '/landing', to:"landing#show"

  get '/login', to:"login#login"

  get '/main', to:"main#index"

  get '/albums', to:"albums#index"

  get 'friends/index'
  get '/friends', to:"friends#index"
  post '/friends/index'
  post '/friends', to:"friends#index"
  get 'friends/results'
  post 'friends/results'

  post 'users/edit_pic'

   root 'landing#show'

end

app/models/album.rb
class Album < ActiveRecord::Base
  has_attached_file :cover, {styles: { small: "64x64", med: "100x100", large: "200x200" },
                    :url  => "/assets/images/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/albums/:id/:style/:basename.:extension"}
  validates_attachment_content_type :cover, content_type: /\Acover\/.*\Z/

  #has_many :photos

  belongs_to :user
  #belongs_to :album_view
end

app/models/album_view.rb
class AlbumView < ActiveRecord::Base
  #has_many :users, through: :albums
  belongs_to :user
  belongs_to :album
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_login
  before_action :set_album, only: [:show, :destroy]

  respond_to :html, :js

  helper AlbumsHelper

  def index
	  @nav_bar = true
    # Grab all the albums of the current user
    @albums = Array.new
    #all albums with name and "hidden" ones
    owned_albums = Album.where(user_id: current_user.id)
    owned_albums.each do |a|
        @albums.push([a, find_album_name(a)])
    end
    # @albums = Album.where(user_id: current_user.id)
    #albums-views
    #decide who to share albums with
    #then upon choosing a user, create albums-view--> connects album with friend?
  end

  def new
    @album = Album.new
    @users = User.all

  end

  def create
    #Determine public/private access of album
    # if params[:opts] == "Public"
    #   access = true
    # elsif params[:opts] == "Private"
    #   access = false
    # end

    #!!!!!#Changed
    #make private albums by default
    access = false;

    #!!!!!#Changed
    # Create a new album where it is tied to the current user

    @album = Album.new(:user_id => current_user.id, :album_name => "Unnamed Album", :isPublic => access)
    #!!!!!#Changed
    @owner = AlbumView.new(:user_id => current_user.id)

    #Need to create an album view for each friend
    if !access && params[:friends]
     #album id stays empty if it's just view access,
    #if upload is granted, then it will be updated when the friend wants
    #to add to it - in the friends page (but the permissions will have to be checked)

    params[:friends].each do |f| #right now same permission at once--see if i can change this!
      if params[:access] == "0"
        @album_view = AlbumView.new(:user_id => f, :view_upload_access => 0)
        @album_view.save
      elsif params[:access] == "1"
        @album_view = AlbumView.new(:user_id => f, :view_upload_access => 1)
        @album_view.save
      end
    end
  end

    respond_to do |format|
      if @album.save
        if !access
          #!!!!!#Changed
          #@album_view.update_attribute(:album_view_id, @album.id)
          @owner.update_attribute(:album_id, @album.id) #for owner, album_view_id=album_id
          @owner.update_attribute(:album_view_id, @album.id)
          @owner.update_attribute(:view_upload_access, 1)
        end

        format.html { redirect_to album_path(@album, :friends_shared => params[:friends]), notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
        format.js { render :layout=>false}
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
        format.js {render :layout=>false}
      end
    end
  end



  # Grab all the photos in the current album to show them
  def show
      @nav_bar=true
      @photo = Photo.new
      @album = Album.find(params[:id])
      @album_name = find_album_name(@album)
      @view_only = false

      if @album.user_id != current_user.id
        @is_view = true
        @view_only = true
      # elsif AlbumView.where(album_id: @album.id)
      #   @is_view = true
      else
        @is_view = false
      end
      if @album.album_name.eql?("*empty")
        @is_view = true
      end

      @photos = Photo.where(album_id: params[:id])
      @other_photos = find_all_photos(@album)
      # puts @other_photos
      # gets

      @friends_shared = params[:friends_shared]

      #If user changes pub/private settings
      if params[:opts]
        if params[:opts] == "Public"
          @album.update_attribute(:isPublic, true)
          #Delete from album view database
          AlbumView.where(album_view_id:@album.id).each do |av|
            av.destroy #make sure this is what I want to be doing...
          end
        elsif params[:opts] == "Private"
          @album.update_attribute(:isPublic, false)
          #Create for owner - selected friends, if any, are added below
          AlbumView.first_or_create(:user_id => current_user.id, :view_upload_access => 1, :album_id => @album.id, :album_view_id => @album.id)
        end
      end

      #Updates in view
      if @album.isPublic
        @pub_private = "Public"
      else
        @pub_private = "Private"
      end

      #Adding new friends - same as create
      if params[:friends]
        #copied from above:
          params[:friends].each do |f| #right now same permission at once--see if i can change this!
            if params[:access] == "0"
              @album_view = AlbumView.new(:user_id => f, :view_upload_access => 0, :album_view_id => @album.id)
              @album_view.save
            elsif params[:access] == "1"
              @album_view = AlbumView.new(:user_id => f, :view_upload_access => 1, :album_view_id => @album.id)
              @album_view.save
            end
        end
      end

      #Remove friend from AlbumView db
      if params[:unshare]
        AlbumView.where(album_view_id:@album.id).each do |av|
          if av.user_id == params[:unshare].to_i
            #Album.find(av.album_id).destroy
            av.destroy
          end
        end
      end

      #Update access of a friend already shared with
      if params[:change_access]
        #find album_view and update the access
        AlbumView.where(album_view_id: @album.id).each do |av|
          if av.user_id == params[:friend].to_i
              if params[:change_access] == "View Only"
                av.update_attribute(:view_upload_access, 0)
                Album.where(id: av.album_id, album_name: "*empty", user_id: params[:friend].to_i).destroy_all
                av.update_attribute(:album_id, nil)
              elsif params[:change_access] == "View and Upload"
                av.update_attribute(:view_upload_access, 1)
                sharable = Album.where(album_name: "*empty", user_id: params[:friend].to_i, isPublic: false).first
                if sharable.nil?
                  sharable = Album.create(album_name: "*empty", user_id: params[:friend].to_i, isPublic: false)
                end
                av.update_attribute(:album_id, sharable.id)
              end
          end
        end
      end

  end

  def edit
    # why is it deleting under edit?????
    # identify the user first...
    # Album.find(params[:id]).destroy
    # redirect_to :action => 'index'
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])
    @album.update(:album_name=> params[:a_name], :defaultx=> params[:xcoord], :defaulty=>params[:ycoord]);


    redirect_to album_form_album_path
     # if @album.save
    #   redirect_to album_form_album_path
    # else
    #   redirect_to album_form_album_path
    # end
  end

  def form
    @album = Album.find(params[:id])
    render :layout => false
  end

  def map
    # Show the navigation bar
      @nav_bar = true
      @album_name = Album.find(params[:id]).album_name
      @owner = User.find(Album.find(params[:id]).user_id)
      #declare variables we will return to view
      @unmapped=[];
      @unmapped_album=[];

      #declare local variables
      photo_ids=[];     #ID's of photos to be mapped
      album_ids=[];     #ID's of albums to map
      x_coord=[];       #X-Coordinates matching the order of photo_ids
      y_coord=[];       #Y-Coordinates matching the order of photo_ids
      links=[];         #URL links matching the order of photo_ids
      albums=[];        #ID's of albums matching the order of photo_ids
      color=[];         #index of color outline for the album



      # For each album, push all the photos and links into the arrays
      album = Album.find(params[:id])
      photo_ids = Photo.where(:album_id =>params[:id])
      photo_ids.each do |t|
        #only show unmapped photos that belong to the user
        if (t.x_coord == nil) && (album.user_id==current_user.id)
          @unmapped_album.push(params[:id])
          @unmapped.push(t)
        #ignore unmapped photos of the other users
        elsif (t.x_coord ==nil)
        #For everything else, save the url, coordinates, and which album its from
        else
          links.push(t.image.url)
          x_coord.push(t.x_coord)
          y_coord.push(t.y_coord)
          albums.push(params[:id])
        end
      end


      i =0;
      color_map = Hash.new
      albums.each do |a|
        if (color_map[a]==nil)
          color_map[a]=i;
          color.push(i);
          i=i+1;
        else
          color.push(color_map[a])
        end
      end

      x=Hash.new
      y=Hash.new
      album_ids=Hash.new

      for i in 0..(links.length)
        x[links[i]]=x_coord[i];
        y[links[i]]=y_coord[i];
        album_ids[links[i]]=albums[i];
      end

      gon.color_map = JSON.generate(color_map)
      gon.x1 = JSON.generate(x)
      gon.y1 = JSON.generate(y)
      gon.album_ids = JSON.generate(album_ids)


      gon.x = x_coord
      gon.y = y_coord
      gon.img = links
      gon.albums = albums
      gon.unmapped = @unmapped.length>0
      gon.color = color
  end

  def destroy
    #destroy related records in AlbumView & Album
    views = AlbumView.where(album_id: @album.id)
    if !views.empty?
      views.each do |view|
        uploaders = AlbumView.where(album_view_id: view.album_view_id, view_upload_access: 1)
        if uploaders.size == 1
        #which case all entries in the view should be deleted
          AlbumView.where(album_view_id: view.id).destroy_all
        else
        #only delete THE entry
          AlbumView.where(album_view_id: view.id, view_upload_access: 1, user_id: current_user.id).destroy_all
          if !@album.album_name.eql?("*empty")
            #if this is the name-holder, give the name to the next in album_id
            view_name = @album.album_name
            replacement_id = uploaders.where.not(user_id: current_user.id).first.album_id
            Album.find(replacement_id).update(album_name: view_name)
          end
        end

app/controllers/api/v1/albums_controller.rb
class Api::V1::AlbumsController < Api::V1::BaseController

  def show
      album = Album.where( id: params[:id], user_id: params[:user_id])
      if not album.empty?
        render json: album.to_json
      else
        render :json => { :errors => "No Album Found" }, :status => 422
      end
  end

  def index
    albums = Album.where(user_id: params[:user_id])
    if not albums.empty?
      render json: albums.to_json
    else
      render :json => { :errors => "No Albums Found" }, :status => 422
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
	def get_friends
		@all_friends = Array.new
		@user_friender = Popular::Friendship.where(popular_model_id:current_user)
	    @user_friendee = Popular::Friendship.where(friend_id:current_user)

	    #might need to check if user friender/friendee is null
	    @user_friender.each do |f|
	    if f.did_accept != nil
	    		User.find(f.friend_id).first_name
	        	@all_friends.push(User.find(f.friend_id))
	    	end
	    end

	    @user_friendee.each do |f|
	    	if f.did_accept != nil
	            User.find(f.popular_model_id).first_name
	            @all_friends.push(User.find(f.popular_model_id))
	        end
	    end
	    return @all_friends
	end

	def sample_photo id
		photo = Photo.where(album_id: id).sample
	end

end

app/views/albums/_edit.html.erb
</div>
<div class="col-md-6 col-md-offset-9">
  <%= link_to "View Map" , map_album_path, class: "btn btn-primary"%>
  <%= render "upload_button" unless @view_only%>
  <%= button_tag(type: 'button', class: "btn btn-primary", "data-toggle"=> "modal", "data-target"=> "#change_privacy") do %>
      Privacy Settings
  <% end %>
</div>
<!--Modal Alert to Change Privacy  -->
<div class="modal fade" tabindex="-1" role="dialog" id="change_privacy">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Select Privacy Setting for this Album</h4>
      </div>
      <div class="modal-footer">
        <body onload="showFriends()">
        <%= form_tag(album_path, method: "get")  do %>
          <%= select_tag("opts", options_for_select(["Public", "Private"], selected: @pub_private), :onchange => "showFriends()") %> <!--Need Javascript here when switching from public/private -->
        <div id="f1" style="display:none">
          <% @friends_shared = Array.new %>
          <% @friend_access = Hash.new %>
          <% AlbumView.where(album_view_id:@album.id).each do |av| %>
            <% if av.user_id != current_user.id %>
              <% @friends_shared.push(av.user_id) %>
              <% @access = nil %>
              <% if av.view_upload_access == 0 %>
                <% @access = "View Only" %>
              <% elsif av.view_upload_access == 1 %>
                <% @access = "View and Upload" %>
              <% end %>
              <% @friend_access[av.user_id] = @access %>
            <% end %>
          <% end %>

            <% if @friends_shared %>

                <% get_friends.each do |f| %>
                  <% if @friends_shared.include? f.id %>
                    <div> <%= f.first_name %> <%= f.last_name %>
                    <!--show which access privilege the friend has, and give option to change that setting -->
                        <%= select_tag("change_access", options_for_select(["View Only", "View and Upload"], selected: @friend_access[f.id])) %>
                        <%= hidden_field_tag(:friend, f.id) %>

                        <%= link_to "Unshare", {:controller => "albums", :action => "show", :unshare => f.id}, method: "get" %>
                      </div>

                  <% else %>
                    <!--copied from new -->
                    <select name="friends[]" multiple="multiple">
                      <% get_friends.each do |f| %>
                        <option onclick="test()", value= <%= f.id %> >
                          <%= f.first_name %> <%= f.last_name %>
                        </option>
                      <% end %>
                    </select>
                  <% end %>
                <% end %>

                <div id="access" style="display:none">
                  <select name="access">
                    <option value = "0">View Only</option>
                    <option value = "1">View and Upload</option>
                  </select>
                </div>

              <!--<#% end %>-->
            <% end %>
        </div>
            <%= submit_tag("Update") %>
        <% end %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/albums/_form.html.erb
<%= form_for @album, remote: true, :authenticity_token=> true, html: {multipart: true, hidden:false} do |f| %>
  <input id="a_name" name="a_name" type="text" value="<%= @album.album_name%>"/>
  <input id="xcoord" name="xcoord" type="text" value="<%= @album.defaultx%>"/>
  <input id="ycoord" name="ycoord" type="text" value="<%= @album.defaulty%>"/>
  <%= f.submit 'Save', :id=>"submit_album_name_edit"%>
<% end %>

app/views/albums/_index.html.erb
<% if @albums.blank? %>
  <h3 class="no_albums_header text-center">No Albums to Display </h3>
<% else %>
  <% @albums.each do |album| %>
    <div class="col-sm-4 col-md-2">
      <div class="thumbnail text-center">
        <%if sample_photo(album.first.id)%>
          <%=image_tag sample_photo(album.first.id).image.url(:med), id:"album_image"%>
        <%else%>
          <%=image_tag "480px-Placeholder.png", id:"placeholder"%>
        <%end%>
        <div class="caption overflow">
          <p>
            <%= link_to album.last, album.first, id: "album_name_listing"%>
          </p>
        </div>
        <br/>
        <%= link_to 'Delete', album.first, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger"%>
      </div>
    </div>
  <% end %>
<% end %>

app/views/albums/_upload_button.html.erb
  <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#photo_upload" aria-expanded="false" aria-controls="photo_upload" id="photo-upload-toggle">
    Upload 
  </button>

app/views/albums/_uploading.html.erb
<div class="collapse text-center" id="photo_upload">
  <h1> Upload Photos </h1>
  <!--Form to upload multiple photos  -->
  <%= form_for @photo, html: {multipart: true} do |f| %>
    <div class="form-group col-md-offset-5">
      <%= file_field_tag "images[]", type: :file, multiple: true, class: "upload_button"%>
    </div>
    <%= f.submit 'Upload', class:"btn btn-primary" %>
  <% end %>
</div>

app/views/albums/create.js.erb
alert("SDFDS");
$("#a").html("AAAAAA");

app/views/albums/edit.html.erb
<h1>Edit Album</h1>

<%= image_tag @album.cover.url(:med) %>

<%= form_for @album, :html => {:multipart => true} do |a| %>
  <div class="form-group">
    <%= a.label :cover %>
    <%= a.file_field :cover %>
    <!-- <#%= file_field_tag "cover", type: :file%> -->
  </div>
  <%= a.submit 'Upload Cover' %>

<% end %>

app/views/albums/edit.js.erb
$("#product-modal").html("<%= escape_javascript(render 'edit') %>")
$("#product-modal").modal("show")

app/views/albums/form.html.erb
<%= form_for @album, remote: true, :authenticity_token=> true, html: {multipart: true, hidden:false} do |f| %>
  <input id="a_name" name="a_name" type="text" value="<%= @album.album_name%>"/>
  <input id="xcoord" name="xcoord" type="text" value="<%= @album.defaultx%>"/>
  <input id="ycoord" name="ycoord" type="text" value="<%= @album.defaulty%>"/>
  <%= f.submit 'Save', :id=>"submit_album_name_edit"%>
<% end %>

app/views/albums/map.html.erb
<%=render "layouts/preloader" %>
<%= include_gon %>
<div id="map_key" hidden=true>../</div>

<div id="main_header" class="col-mid-8">
    <h1> <%=@album_name%></h1>
    <h5> Album By <%=@owner.first_name%></h5>
</div>

<%=link_to "View as List", album_path, class:"btn btn-primary"%>

<div class="container">
  <div class = "row">
    <% if @unmapped.blank? %>
      <div id="map" class="col-md-12 col-sm-12 col-xs-12"></div>
    <% else %>
      <div id="map" class="col-md-9 col-sm-10"></div>
      <div class="uncoordinated-photos col-md-3 col-sm-3 col-md-offset-1" >
        <div class="panel panel-primary "  >
          <div class="panel-heading">
            <h3>Your Photos with No Coordinates</h3>
            <h5>Select a photo and click a place to map it</h5>
          </div>
          <div class="panel-body">
            <% counter=0 %>
            <% @unmapped.each do |p| %>
              <%=image_tag p.image.url(:med), class:"unmapped_photo", id: p.id, data:{album: @unmapped_album[counter]} %>
              <%counter=counter+1%>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>

<%= javascript_include_tag "/js/jquery.js" %>
<%= javascript_include_tag "/js/bootstrap.min.js" %>
<%= javascript_include_tag "/js/map.js" %>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDmZ0UjQy-J4ELU51wczIAqv9nlywKb4mA&callback=initMap" async defer></script>

<!-- iFrame to the form to drag and drop pictures to remap them -->
<iframe id="ifrm" src="/main/form" hidden=false></iframe>


<!-- At the bottom so it is executed only when the above code is run -->
<%= javascript_include_tag "/js/dragdrop.js" %>
<%= javascript_include_tag "main.js" %>

app/views/albums/new.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name the new album:</strong>

  <p> Also, choose if you would like to make it public or private, public meaning any of your friends can see the album, and private meaning you can limit viewing and/or uploading to specific users (or just yourself) </p>
</p>

<%= form_tag "create", method: "post"  do %>
  <%= text_field_tag 'album_name' %>
  <%= select_tag("opts", options_for_select(["Public", "Private"], selected: :option), :onchange => "showFriends()") %>

 <!-- <select id = "opts", onchange="showFriends()">
  	<option value="0">Public</option>
  	<option value="1">Private</option>
  </select>-->

  <div id="f1" style="display:none">
    <!--<form name="form1">-->
    	<% if get_friends %>
	        <select name="friends[]" multiple="multiple">
	            <% get_friends.each do |f| #helper for all friends%>
	            	<option onclick="test()", value= <%= f.id %> >
	            		<%= f.first_name %> <%= f.last_name %>
	            	</option>

	            <% end %>
	        </select>
	    <% end %>
    <!--</form>-->
</div>

<div id="access" style="display:none">
	<select name="access">
		<option value = "0">View Only</option>
		<option value = "1">View and Upload</option>
	</select>
</div>

  <%= submit_tag("Create") %>
<% end %>

<% if @photos.blank? %>
  <p> You don't have any photos yet </p>
  <p> Your ID: <%= current_user.id %> </p>
<% else %>
  <h2><% @photos.count %></h2>
<% end %>


<%= link_to 'Back', albums_path %>

<!--

<script language="javascript">
    window.location.href = "/albums"
</script> -->

<script type="text/javascript">
    function showFriends() {
        var selopt = document.getElementById("opts").value;
    	if (selopt == "Private") {
            document.getElementById("f1").style.display = "block";
        }
        else {
        	document.getElementById("f1").style.display = "none";

        }
    }

    function test() {
    	document.getElementById("access").style.display = "block";
    }
</script>

app/views/albums/new.js.erb
$("#new_album").hide().after('<%= j render("form") %>')
alert("###");
$("#product-modal").html("<%= escape_javascript(render 'new') %>")
$("#product-modal").modal("show")

app/views/albums/show.html.erb
<%= javascript_include_tag "/js/jquery.js" %>
<%= javascript_include_tag "/js/change_to_edit.js" %>

<section id="portfolio" class="primary">
<br/>
<p id="notice"><%= notice %></p>
<section id="portfolio" class="primary">

<iframe id="ifrm" src="/albums/<%= @album.id%>/form" style="width:70%;" hidden=true></iframe>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-10">
      <% if not @is_view %>
        <%= render "edit"%>
      <% else %>
        </div>
        <div class="col-md-3 col-md-offset-10">
          <%= link_to "View Map" , map_album_path, class: "btn btn-primary"%>
          <%= render "upload_button" unless @view_only%>
        </div>
      <%end%>
      <span id="album_name_parent">
        <h3 id="album_name" onclick="edit(<%@view_only%>)">
          <%=@album_name%>
        </h3>
        <% if @album_name == "Unnamed Album" and not @view_only %>
          <h5 class = "text-center" id="change_notice">Click the Name Above to Change It</h5>
        <%end%>
        <hr class="small">
        <%= render "uploading" unless @view_only%>
      </span>
  </div>


<div class = "row">
  <div id="photo_container">
    <!--Check to see if there are photos, then display the photos in the album  -->
    <% if @photos.blank? && @other_photos.blank? %>
      <p> No photos yet </p>
    <% else %>
      <% @photos.each do |p| %>
        <span class="picture thumbnail col-md-2 col-md-offset-1 text-center">
          <%=image_tag p.image.url(:large), id:"image"%>
          <br/>
          <%= link_to 'Delete', delete_photo_path(@album, p), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger"%>
        </span>
      <% end %>
        <% @other_photos.each do |p| %>
        <span class="picture thumbnail col-md-2 col-md-offset-1">
          <%=image_tag p.image.url(:large), id:"image"%>
        </span>
      <% end %>
    <% end%>
    </div>
  </div>

  <%= render "uploading" unless @view_only%>

</div>






<!--Link to new_album_photo_path  -->
<!-- <%= button_to 'Upload Photos!', new_photo_path %> -->

<%= link_to 'Back', albums_path %>
</section>
<!--copied from new, needs to go in js-->
<%javascript_include_tag "albums.js" %>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDmZ0UjQy-J4ELU51wczIAqv9nlywKb4mA&callback=initMap" async defer></script>

app/views/albums/update.js.erb
<%= render "save" %>